openapi: 3.0.3
info:
  title: Check Habit - Auth API
  description: Authentication API for Check Habit application
  version: 1.0.0
servers:
  - url: /api
    description: API

paths:
  /auth/register:
    post:
      summary: Register a new user
      operationId: Register
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      summary: Authenticate user
      operationId: Login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/google/login:
    get:
      summary: Get Google Login URL
      operationId: GoogleLogin
      tags:
        - Auth
      responses:
        '200':
          description: Google Login URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean, example: true }
                  data:
                    type: object
                    properties:
                      url: { type: string }

  /auth/google/callback:
    post:
      summary: Handle Google Callback
      operationId: GoogleCallback
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [code]
              properties:
                code: { type: string }
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout:
    post:
      summary: Logout current session
      operationId: Logout
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'

  /auth/logout-all:
    post:
      summary: Logout from all devices
      operationId: LogoutAll
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutAllRequest'
      responses:
        '200':
          description: Logout all successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutAllResponse'

  /auth/sessions:
    get:
      summary: List all user sessions
      operationId: ListSessions
      description: |
        Get a paginated list of sessions for the authenticated user.

        **Pagination**: Use `page` and `per_page` query parameters.
      tags:
        - Auth
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number (1-indexed)
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: per_page
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: include_blocked
          in: query
          description: Include blocked sessions
          schema:
            type: boolean
            default: false
        - name: include_expired
          in: query
          description: Include expired sessions
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: A paginated list of sessions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSessionListWrapper'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/profile:
    get:
      summary: Get current user profile
      operationId: GetProfile
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update user profile
      operationId: UpdateProfile
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/change-password:
    post:
      summary: Change user password
      operationId: ChangePassword
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/verify-email:
    post:
      summary: Verify email address
      operationId: VerifyEmail
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/resend-verification:
    post:
      summary: Resend verification email
      operationId: ResendVerification
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendVerificationRequest'
      responses:
        '200':
          description: Verification email sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/forgot-password:
    post:
      summary: Request password reset
      operationId: ForgotPassword
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Password reset email sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/reset-password:
    post:
      summary: Reset password
      operationId: ResetPassword
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/sessions/other:
    delete:
      summary: Revoke all other sessions
      operationId: RevokeOtherSessions
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Other sessions revoked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/export:
    get:
      summary: Export user data (GDPR)
      operationId: ExportUserData
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User data exported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    description: The exported data payload
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/account:
    delete:
      summary: Delete user account
      operationId: DeleteAccount
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  description: Password confirmation for security
      responses:
        '200':
          description: Account deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad request or invalid password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
        email:
          type: string
        password:
          type: string
          minLength: 8

    RegisterResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: User registered successfully
        data:
          type: object
          properties:
            user_id:
              type: string
              format: uuid
            email:
              type: string
              format: email
            name:
              type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            access_token:
              type: string
            refresh_token:
              type: string
            session_id:
              type: string
              format: uuid
            user_id:
              type: string
              format: uuid
            expires_at:
              type: integer
              format: int64

    LogoutRequest:
      type: object
      required:
        - session_id
      properties:
        session_id:
          type: string
          format: uuid

    LogoutAllRequest:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          format: uuid

    LogoutResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: logged out successfully

    LogoutAllResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: logged out from all devices successfully

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: object
          properties:
            code:
              type: string
            details:
              type: object

    # Pagination schema
    Pagination:
      type: object
      description: Pagination metadata for list responses
      properties:
        has_previous_page:
          type: boolean
          description: Whether there is a previous page
        has_next_page:
          type: boolean
          description: Whether there is a next page
        current_page:
          type: integer
          description: Current page number (1-indexed)
        per_page:
          type: integer
          description: Number of items per page
        total_data:
          type: integer
          description: Total number of items across all pages
        total_data_in_current_page:
          type: integer
          description: Number of items in the current page
        last_page:
          type: integer
          description: Last page number
        from:
          type: integer
          description: Index of the first item in the current page (1-indexed)
        to:
          type: integer
          description: Index of the last item in the current page

    # Session DTO
    Session:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        user_agent:
          type: string
        client_ip:
          type: string
        is_blocked:
          type: boolean
        expires_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        is_active:
          type: boolean
        is_current:
          type: boolean

    # Paginated Session List Wrapper
    PaginatedSessionListWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Session'
        meta:
          type: object
          properties:
            pagination:
              $ref: '#/components/schemas/Pagination'

    # Profile DTOs
    ProfileResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: object
          properties:
            user_id:
              type: string
              format: uuid
            name:
              type: string
            email:
              type: string
            timezone:
              type: string
              description: User timezone in IANA format (e.g., Asia/Jakarta, America/New_York)
              example: Asia/Jakarta
            created_at:
              type: string
              format: date-time

    UpdateProfileRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
        email:
          type: string
        timezone:
          type: string
          description: User timezone in IANA format (e.g., Asia/Jakarta, America/New_York)
          example: Asia/Jakarta

    ChangePasswordRequest:
      type: object
      required:
        - current_password
        - new_password
      properties:
        current_password:
          type: string
        new_password:
          type: string
          minLength: 8

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string

    VerifyEmailRequest:
      type: object
      required:
        - email
        - code
      properties:
        email:
          type: string
        code:
          type: string

    ResendVerificationRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string

    ForgotPasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string

    ResetPasswordRequest:
      type: object
      required:
        - email
        - code
        - new_password
      properties:
        email:
          type: string
        code:
          type: string
        new_password:
          type: string
          minLength: 8
