openapi: 3.0.3
info:
  title: Habits API
  description: API for managing habits
  version: 1.0.0
servers:
  - url: /api
paths:
  /habits:
    get:
      summary: List all habits
      operationId: listHabits
      description: |
        Get a paginated list of habits with comprehensive filtering options.

        **Pagination**: Use `page` and `per_page` query parameters.

        **Filtering**:
        - `active`/`inactive` - filter by status
        - `keyword` or `q` - search in name and description
        - `start_date`/`end_date` - filter by creation date (format: YYYY-MM-DD)

        **Sorting**: Use `sort_by` (name, created_at, updated_at) and `sort_direction` (asc, desc).
      parameters:
        - name: page
          in: query
          description: Page number (1-indexed)
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: per_page
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: keyword
          in: query
          description: Search keyword (searches in name and description)
          schema:
            type: string
        - name: active
          in: query
          description: Filter by active status
          schema:
            type: boolean
        - name: inactive
          in: query
          description: Filter by inactive status
          schema:
            type: boolean
        - name: start_date
          in: query
          description: Filter habits created on or after this date
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: Filter habits created on or before this date
          schema:
            type: string
            format: date
        - name: sort_by
          in: query
          description: Column to sort by
          schema:
            type: string
            enum: [name, created_at, updated_at, is_active]
        - name: sort_direction
          in: query
          description: Sort direction
          schema:
            type: string
            enum: [asc, desc]
            default: asc
      responses:
        '200':
          description: A paginated list of habits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedHabitListWrapper'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new habit
      operationId: createHabit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHabitRequest'
      responses:
        '201':
          description: The created habit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitWrapper'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /habits/{habitId}:
    get:
      summary: Get a habit by ID
      operationId: getHabit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The habit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitWrapper'
        '404':
          description: Habit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update a habit
      operationId: updateHabit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateHabitRequest'
      responses:
        '200':
          description: The updated habit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitWrapper'
        '404':
          description: Habit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a habit
      operationId: deleteHabit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Habit deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '404':
          description: Habit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /habits/{habitId}/activate:
    post:
      summary: Activate a habit
      operationId: activateHabit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Habit activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /habits/{habitId}/deactivate:
    post:
      summary: Deactivate a habit
      operationId: deactivateHabit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Habit deactivated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /habits/{habitId}/stats:
    get:
      summary: Get habit statistics
      operationId: getHabitStats
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Habit statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitStatsWrapper'

  /habits/{habitId}/logs:
    post:
      summary: Log a habit
      operationId: logHabit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogHabitRequest'
      responses:
        '201':
          description: Habit logged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitLogCreatedWrapper'
    get:
      summary: Get habit logs
      operationId: getHabitLogs
      description: |
        Get a paginated list of habit logs with filtering options.

        **Pagination**: Use `page` and `per_page` query parameters.

        **Filtering**:
        - `start_date`/`end_date` - filter logs by date range (format: YYYY-MM-DD)
        - `keyword` or `q` - search in notes

        **Sorting**: Use `sort_by` (log_date, created_at, count) and `sort_direction` (asc, desc).
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          description: Page number (1-indexed)
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: per_page
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: start_date
          in: query
          description: Filter logs on or after this date
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: Filter logs on or before this date
          schema:
            type: string
            format: date
        - name: keyword
          in: query
          description: Search keyword (searches in note)
          schema:
            type: string
        - name: sort_by
          in: query
          description: Column to sort by
          schema:
            type: string
            enum: [log_date, created_at, count]
        - name: sort_direction
          in: query
          description: Sort direction
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Paginated list of habit logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedHabitLogsWrapper'

  /habit-logs/{logId}:
    put:
      summary: Update a habit log
      operationId: updateHabitLog
      parameters:
        - name: logId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateHabitLogRequest'
      responses:
        '200':
          description: Habit log updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
    delete:
      summary: Delete a habit log
      operationId: deleteHabitLog
      parameters:
        - name: logId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Habit log deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /dashboard:
    get:
      summary: Get user dashboard
      operationId: getDashboard
      responses:
        '200':
          description: User dashboard data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardWrapper'

  /analytics/weekly:
    get:
      summary: Get weekly analytics data
      operationId: getWeeklyAnalytics
      description: |
        Returns habit completion data for the last 7 days.
        Each day includes the number of habits completed and completion percentage.
      responses:
        '200':
          description: Weekly analytics data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeeklyAnalyticsWrapper'

components:
  schemas:
    # Pagination schema
    Pagination:
      type: object
      description: Pagination metadata for list responses
      properties:
        has_previous_page:
          type: boolean
          description: Whether there is a previous page
        has_next_page:
          type: boolean
          description: Whether there is a next page
        current_page:
          type: integer
          description: Current page number (1-indexed)
        per_page:
          type: integer
          description: Number of items per page
        total_data:
          type: integer
          description: Total number of items across all pages
        total_data_in_current_page:
          type: integer
          description: Number of items in the current page
        last_page:
          type: integer
          description: Last page number
        from:
          type: integer
          description: Index of the first item in the current page (1-indexed)
        to:
          type: integer
          description: Index of the last item in the current page

    # Paginated List Wrappers
    PaginatedHabitListWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Habit'
        meta:
          type: object
          properties:
            pagination:
              $ref: '#/components/schemas/Pagination'

    PaginatedHabitLogsWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/HabitLog'
        meta:
          type: object
          properties:
            pagination:
              $ref: '#/components/schemas/Pagination'

    # Simple Wrappers (for single items or non-paginated responses)
    HabitWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          $ref: '#/components/schemas/Habit'

    HabitListWrapper:
      type: object
      deprecated: true
      description: Deprecated. Use PaginatedHabitListWrapper instead.
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Habit'

    HabitLogCreatedWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: object
          properties:
            log_id:
              type: string
              format: uuid

    HabitLogsWrapper:
      type: object
      deprecated: true
      description: Deprecated. Use PaginatedHabitLogsWrapper instead.
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/HabitLog'

    HabitStatsWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          $ref: '#/components/schemas/HabitStats'

    DashboardWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          $ref: '#/components/schemas/Dashboard'

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Operation successful

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: object
          properties:
            code:
              type: string
            details:
              type: object

    # Domain Models
    Habit:
      type: object
      required:
        - id
        - name
        - created_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        frequency:
          type: string
          enum: [daily, weekly, monthly]
        target_count:
          type: integer
        reminder_time:
          type: string
          description: Daily reminder time in HH:MM format (e.g., "08:00")
          example: '08:00'
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateHabitRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        frequency:
          type: string
          example: 'daily'
        target_count:
          type: integer
          example: 1
        reminder_time:
          type: string
          description: Daily reminder time in HH:MM format
          example: '08:00'

    UpdateHabitRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        frequency:
          type: string
        target_count:
          type: integer
        reminder_time:
          type: string
          description: Daily reminder time in HH:MM format
          example: '08:00'

    LogHabitRequest:
      type: object
      required:
        - log_date
        - count
      properties:
        log_date:
          type: string
          format: date
        count:
          type: integer
        note:
          type: string

    UpdateHabitLogRequest:
      type: object
      properties:
        count:
          type: integer
        note:
          type: string
        log_date:
          type: string
          format: date-time
          description: Log date in ISO 8601 format

    HabitLog:
      type: object
      properties:
        id:
          type: string
          format: uuid
        habit_id:
          type: string
          format: uuid
        log_date:
          type: string
          format: date
        count:
          type: integer
        note:
          type: string
        created_at:
          type: string
          format: date-time

    HabitStats:
      type: object
      properties:
        total_logs:
          type: integer
        current_streak:
          type: integer
        longest_streak:
          type: integer

    Dashboard:
      type: object
      properties:
        active_habits_count:
          type: integer
        total_logs_today:
          type: integer
        current_streak:
          type: integer
        longest_streak:
          type: integer
        weekly_completion:
          type: integer
          description: Weekly completion percentage (0-100)
        total_logs:
          type: integer
          description: Total habit logs all time

    WeeklyAnalyticsWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          $ref: '#/components/schemas/WeeklyAnalytics'

    WeeklyAnalytics:
      type: object
      properties:
        days:
          type: array
          items:
            $ref: '#/components/schemas/DailyAnalytics'
        average_completion:
          type: integer
          description: Average completion percentage for the week

    DailyAnalytics:
      type: object
      properties:
        day_name:
          type: string
          description: Day of week name (Mon, Tue, etc.)
        date:
          type: string
          format: date
        logs_count:
          type: integer
          description: Number of habit logs on this day
        completion_percentage:
          type: integer
          description: Completion percentage for this day (0-100)
