openapi: 3.0.3
info:
  title: Notifications API
  description: API for managing in-app notifications
  version: 1.0.0
servers:
  - url: /api
paths:
  /notifications:
    post:
      summary: Create a notification (for testing/admin)
      operationId: createNotification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - message
                - type
              properties:
                title:
                  type: string
                message:
                  type: string
                type:
                  type: string
                  enum: [streak_milestone, habit_reminder, achievement, system, welcome]
                data:
                  type: object
      responses:
        '201':
          description: Notification created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      security:
        - bearerAuth: []
    get:
      summary: List user notifications
      operationId: listNotifications
      description: Get a paginated list of notifications for the current user
      parameters:
        - name: page
          in: query
          description: Page number (1-indexed)
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: per_page
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: unread_only
          in: query
          description: Only return unread notifications
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: A paginated list of notifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedNotificationListWrapper'
      security:
        - bearerAuth: []

  /notifications/unread-count:
    get:
      summary: Get unread notification count
      operationId: getUnreadCount
      description: Get the count of unread notifications
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnreadCountResponse'
      security:
        - bearerAuth: []

  /notifications/{notificationId}/read:
    post:
      summary: Mark notification as read
      operationId: markAsRead
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      security:
        - bearerAuth: []

  /notifications/read-all:
    post:
      summary: Mark all notifications as read
      operationId: markAllAsRead
      responses:
        '200':
          description: All notifications marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      security:
        - bearerAuth: []

  /notifications/{notificationId}:
    delete:
      summary: Delete a notification
      operationId: deleteNotification
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Notification deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      security:
        - bearerAuth: []

  /push/vapid-public-key:
    get:
      summary: Get VAPID public key
      operationId: getVapidPublicKey
      description: Get the VAPID public key for Web Push subscription. This endpoint does not require authentication.
      responses:
        '200':
          description: VAPID public key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VapidPublicKeyResponse'

  /push/subscribe:
    post:
      summary: Subscribe to push notifications
      operationId: subscribePush
      description: Save a Web Push subscription for the current user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushSubscriptionRequest'
      responses:
        '200':
          description: Subscription saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Invalid subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /push/unsubscribe:
    post:
      summary: Unsubscribe from push notifications
      operationId: unsubscribePush
      description: Remove a Web Push subscription
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
              properties:
                endpoint:
                  type: string
                  description: The push subscription endpoint URL
      responses:
        '200':
          description: Subscription removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Pagination:
      type: object
      properties:
        has_previous_page:
          type: boolean
        has_next_page:
          type: boolean
        current_page:
          type: integer
        per_page:
          type: integer
        total_data:
          type: integer
        total_data_in_current_page:
          type: integer
        last_page:
          type: integer
        from:
          type: integer
        to:
          type: integer

    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [streak_milestone, habit_reminder, achievement, system, welcome]
        title:
          type: string
        message:
          type: string
        data:
          type: object
          additionalProperties: true
        is_read:
          type: boolean
        created_at:
          type: string
          format: date-time
        read_at:
          type: string
          format: date-time

    PaginatedNotificationListWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        meta:
          type: object
          properties:
            pagination:
              $ref: '#/components/schemas/Pagination'

    UnreadCountResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: object
          properties:
            count:
              type: integer

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: object
          properties:
            code:
              type: string
            details:
              type: object
              additionalProperties: true

    VapidPublicKeyResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        data:
          type: object
          properties:
            vapid_public_key:
              type: string
              description: VAPID public key for Web Push subscription

    PushSubscriptionRequest:
      type: object
      required:
        - endpoint
        - keys
      properties:
        endpoint:
          type: string
          description: The push subscription endpoint URL from the browser
        keys:
          type: object
          required:
            - p256dh
            - auth
          properties:
            p256dh:
              type: string
              description: Client public key for message encryption
            auth:
              type: string
              description: Authentication secret
